spring.application.name=r2dbc-specification

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/spec
spring.r2dbc.username=postgres
spring.r2dbc.password=root

logging.level.org.springframework.r2dbc=DEBUG
